# Generated by Django 4.1.2 on 2022-10-26 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 10, 26, 20, 8, 30, 820783, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 10, 26, 20, 9, 27, 22773, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
